"""nucleo

Revision ID: 74d31bc22cce
Revises: 
Create Date: 2026-08-31 01:40:24.713678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74d31bc22cce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizacion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('rif', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('es_plataforma', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_table('membresia',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('organizacion_id', sa.Uuid(), nullable=False),
    sa.Column('rol', sa.Enum('direccion', 'secretaria', 'docente', 'representante', 'estudiante', name='rol', native_enum=False, length=32), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizacion.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'organizacion_id', 'rol')
    )
    op.create_table('persona',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organizacion_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('tipo_doc', sa.Enum('cedula_v', 'cedula_e', 'pasaporte', 'partida', 'expediente', name='tipodoc', native_enum=False, length=32), nullable=False),
    sa.Column('numero_doc', sa.String(length=40), nullable=False),
    sa.Column('nombres', sa.String(length=120), nullable=False),
    sa.Column('apellidos', sa.String(length=120), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('sexo', sa.String(length=20), nullable=True),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizacion.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizacion_id', 'tipo_doc', 'numero_doc')
    )
    op.create_index(op.f('ix_persona_organizacion_id'), 'persona', ['organizacion_id'], unique=False)
    op.create_table('alumno',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('persona_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id')
    )
    op.create_table('trabajador',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('persona_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id')
    )
    op.create_table('vinculo_representante',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('representante_persona_id', sa.Uuid(), nullable=False),
    sa.Column('alumno_id', sa.Uuid(), nullable=False),
    sa.Column('parentesco', sa.Enum('madre', 'padre', 'abuelo', 'tutor', name='parentesco', native_enum=False, length=32), nullable=False),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumno.id'], ),
    sa.ForeignKeyConstraint(['representante_persona_id'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('representante_persona_id', 'alumno_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vinculo_representante')
    op.drop_table('trabajador')
    op.drop_table('alumno')
    op.drop_index(op.f('ix_persona_organizacion_id'), table_name='persona')
    op.drop_table('persona')
    op.drop_table('membresia')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('organizacion')
    # ### end Alembic commands ###
